sudo: false

language: go

go:
  - 1.8.x
  - tip

services:
  - docker

before_install:
  - go get github.com/Masterminds/glide

install:
  - glide install -v

script:
  - go build .
  - go list -f '{{if len .TestGoFiles}}"go test -v {{.ImportPath}}"{{end}}' $(go list ./... | grep -v /vendor/) | xargs -i sh -c {}
