sudo: false

language: go

go:
  - 1.9.x
  - tip

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - go build .
  # execute all tests
  - go list -f '{{if len .TestGoFiles}}"go test -race -coverpkg=. -coverprofile={{.Dir}}/.coverprofile -v {{.ImportPath}}"{{end}}' $(go list ./... | grep -v /vendor/) | xargs -i sh -c {}
  - gover
  - goveralls -coverprofile=gover.coverprofile -service travis-ci
